.github/workflows/deploy.yml
packages/design-tokens/package.json
packages/element/package.json
packages/theme-provider/package.json
packages/theme/package.json

Adds the `yarn build` step to the release script

build: add build step to release

---

packages/design-tokens/package.json
packages/element/CHANGELOG.md
packages/element/package.json
packages/theme-provider/CHANGELOG.md
packages/theme-provider/package.json
packages/theme/CHANGELOG.md
packages/theme/package.json

This PR removes the exports property from `package.json`. I also added  `browser` and `module`

fix: update exports

---

.github/workflows/deploy.yml
netlify.toml
package.json

Adds configs and GitHub action for deploying storybook to availity.github.io/availity-element/

build: add storybook deploy

---

.github/workflows/deploy.yml

Added jekyll setting from [this suggestion](https://github.com/storybookjs/storybook/issues/20564#issuecomment-1397103054)

build: add jekyll setting

---

apps/element-storybook/src/buttons.stories.tsx
apps/element-storybook/src/theme-provider.stories.tsx
package.json
packages/button/.npmignore
packages/button/README.md
packages/button/introduction.mdx
packages/button/jest.config.js
packages/button/package.json
packages/button/project.json
packages/button/src/index.ts
packages/button/src/lib/Button.test.tsx
packages/button/src/lib/Button.tsx
packages/button/tsconfig.json
packages/button/tsconfig.spec.json
packages/element/src/index.ts
packages/theme-provider/src/lib/theme-provider.tsx
packages/theme/src/lib/light-theme.ts
tsconfig.json
yarn.lock

feat(theme-provider): fix theme type

feat(theme): update theme for button

---

.github/workflows/deploy.yml
.github/workflows/preview.yml

chore: add PR preview

---

.github/workflows/preview.yml
apps/element-storybook/.storybook/main.ts
apps/element-storybook/src/migration.mdx
apps/element-storybook/src/templates/bs4migration.mdx
package.json
yarn.lock

pulling preview fix out of button pr in case ux takes more time with that.

Preview fix

---

packages/paper/src/lib/Paper.tsx

docs(mui-paper): update docs

---

packages/tooltip/src/lib/Tooltip.stories.tsx
packages/tooltip/src/lib/Tooltip.tsx

Attempt to fix the type errors when using Tooltip

fix(mui-tooltip): change ref type

---

packages/alert/src/lib/Alert.tsx
packages/theme/src/lib/light-theme.ts

- Removed variant and defaulted to standard
- Removed border
- Adjusted the styling to match UX design

Alert Updates

---

apps/element-storybook/src/layouts/sidebar-tables/DataGridSection.tsx
apps/element-storybook/src/layouts/sidebar-tables/SidebarLayout.stories.mdx
apps/element-storybook/src/layouts/sidebar-tables/SidebarLayout.stories.tsx
apps/element-storybook/src/layouts/sidebar-tables/TableData.tsx
apps/element-storybook/src/layouts/sidebar-tables/TablesSection.tsx
package.json
yarn.lock

Includes table and datagrid implementations

Layouts table section

---

packages/design-tokens/src/tokens.json

update semantic secondary values
update grey300

update grey palette and secondary colors

---

packages/design-tokens/src/tokens.json

remapped color.tertiary palette for new colors

update tertiary colors

---

.commitlintrc.json
.github/workflows/commitlint.yml
commitlint.config.js
package.json
yarn.lock

Adds a github action check for commit messages

build: add commitlint github action check

---

package.json
packages/design-tokens/package.json
packages/element/package.json
packages/element/src/index.ts
packages/modal/README.md
packages/modal/introduction.mdx
packages/modal/jest.config.js
packages/modal/package.json
packages/modal/project.json
packages/modal/src/index.ts
packages/modal/src/lib/Modal.stories.tsx
packages/modal/src/lib/Modal.test.tsx
packages/modal/src/lib/Modal.tsx
packages/modal/tsconfig.json
packages/modal/tsconfig.spec.json
tsconfig.base.json
yarn.lock

feat(mui-modal): create modal component

---

packages/button/src/lib/Button.tsx
packages/theme/src/lib/light-theme.ts

Icon will now inherit font size when inside a button

feat(theme): icon inherit button font size in button

---

apps/element-storybook/src/layouts/form/Form.stories.tsx
apps/element-storybook/src/layouts/sidebar-tables/HeaderSection.tsx
packages/alert/src/lib/Alert.tsx
packages/button/src/lib/IconButton.stories.tsx
packages/button/src/lib/IconButton.tsx
packages/card/src/lib/CardActions.stories.tsx
packages/form-utils/src/lib/FieldHelpIcon.tsx
packages/textfield/src/lib/TextField.stories.tsx

hardcode icon button size to medium

refactor(mui-button): remove size prop from icon button

---

packages/theme/src/lib/legacy-theme.ts

fix(theme): missing legacy datepicker outline

---

packages/dialog/src/lib/Dialog.stories.tsx

fix(mui-dialog): pass props to Dialog

---

packages/dialog/src/lib/Dialog.stories.tsx

Fixes accessibility issues with dialog story

fix(mui-dialog): fix accessibility issues in story

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml

This adds `codeql` and `dependabot`.

chore: add dependabot config

---

packages/block-ui/project.json
packages/block-ui/src/lib/BlockUi.stories.tsx

Add a button to allow toggling on and off the blocking

docs(mui-block-ui): add toggle button to stories

---

packages/mock/src/lib/handlers.ts

fix: remove delay for unit tests

---

packages/autocomplete/README.md
packages/autocomplete/package.json
packages/autocomplete/src/lib/AsyncAutocomplete.stories.tsx
packages/autocomplete/src/lib/AsyncAutocomplete.test.tsx
packages/autocomplete/src/lib/AsyncAutocomplete.tsx
packages/autocomplete/src/lib/ProviderAutocomplete.stories.tsx
packages/autocomplete/src/lib/ProviderAutocomplete.test.tsx
packages/autocomplete/src/lib/ProviderAutocomplete.tsx
packages/autocomplete/src/lib/util.ts
packages/mock/src/lib/handlers.ts
packages/mock/src/lib/routes.ts
yarn.lock

I updated the `AsyncAutocomplete` to use `@tanstack/react-query`. This required updating the docs and unit tests.
I also added the `ProviderAutocomplete` component and mocks

feat(mock): add providers

---

packages/autocomplete/src/index.ts

Add `ProviderAutocomplete` export

fix(mui-autocomplete): and provider export

---

.eslintrc.json
jest.polyfills.global.js
packages/autocomplete/src/lib/AsyncAutocomplete.test.tsx
packages/autocomplete/src/lib/AsyncAutocomplete.tsx
packages/autocomplete/src/lib/Autocomplete.stories.tsx
packages/autocomplete/src/lib/Autocomplete.tsx
packages/autocomplete/src/lib/ProviderAutocomplete.tsx
packages/autocomplete/src/lib/util.ts
packages/autocomplete/src/lib/util.tsx
packages/mock/src/lib/handlers.ts
packages/progress/README.md

Added `watchParams` which will refetch the query when they change and `inputValue` which is the value entered to search with

feat(mui-autocomplete): add watchParams and inputValue

---

packages/alert/src/lib/Alert.tsx
packages/icon/src/lib/Iconography.stories.mdx
packages/icon/src/lib/Icons.stories.tsx
packages/icon/src/lib/Icons/Actions.tsx
packages/icon/src/lib/Icons/Form.tsx
packages/icon/src/lib/bs4migration.stories.mdx
packages/stepper/src/lib/StepIcon.tsx
packages/theme/src/lib/legacy-theme.ts
packages/theme/src/lib/light-theme.ts

storybook can't wrap it's stinky head around the OverridableStringUnion

docs(mui-icon): overridablestringunion story controls

---

packages/progress/src/lib/LinearProgress.stories.tsx
packages/stepper/src/lib/Stepper.stories.tsx

fixed 508 issues with stepper and progress stories

fix: resolve accessibility issues in stories

---

packages/icon/src/lib/bs4migration.stories.mdx

knew i was forgetting something

docs: add arrows to icon migration docs

---

packages/favorites/src/lib/FavoriteHeart.tsx
packages/favorites/src/lib/Favorites.tsx
packages/favorites/src/lib/utils.ts
packages/theme/src/lib/legacy-theme.ts
packages/theme/src/lib/light-theme.ts

refactor to accept external user data and avoid making the call internally

refactor favorites EB-832
