Availity/element

- packages/badge/src/lib/Badge.tsx
We have a use case for the nav where we need to use the `success` color variant
> fix(mui-badge): add success color type

- apps/element-storybook/.storybook/preview.tsx
- packages/element/package.json
- packages/element/src/index.ts
- packages/menu/README.md
- packages/menu/introduction.mdx
- packages/menu/jest.config.js
- packages/menu/package.json
- packages/menu/project.json
- packages/menu/src/index.ts
- packages/menu/src/lib/Menu.stories.tsx
- packages/menu/src/lib/Menu.test.tsx
- packages/menu/src/lib/Menu.tsx
- packages/menu/tsconfig.json
- packages/menu/tsconfig.spec.json
- tsconfig.base.json
- yarn.lock
This adds the Menu, MenuItem, and MenuList components.
I also added to the `preview.tsx` to sort the args in the tables and the controls to have the required props first
> feat(mui-menu): add menu component

- packages/divider/src/lib/Divider.stories.tsx
The only scenario that doesn't work is vertical, absolute, and flex - this is due to an issue with the MUI component and is able to be worked around by putting height 100% for the style.
> feat: fixing divider display for flex and absolute options UXDS-310

- packages/avatar/src/lib/Avatar.tsx
if using a src, children on not required
> refactor(mui-avatar): make children arg optional

- apps/element-storybook/.storybook/main.ts
- apps/element-storybook/src/layouts/sidebar-tables/HeaderSection.tsx
- apps/element-storybook/src/layouts/sidebar-tables/SearchSection.tsx
- apps/element-storybook/src/layouts/sidebar-tables/SideNavSection.tsx
- apps/element-storybook/src/layouts/sidebar-tables/SidebarLayout.stories.mdx
- apps/element-storybook/src/layouts/sidebar-tables/SidebarLayout.stories.tsx
- apps/element-storybook/src/layouts/sidebar-tables/TablesSection.tsx
two different versions of documentation given:
1. Autodocs - lists subsections as different stories. Probably better for the interim as we're working. Once all work is done (replaced with availity components) we can move/combine all code into the subsection stories for the corresponding code snippets.
2. MDX - Manual docs, might be better for final documentation once all work is done and combine all code into one file.
thinking of leaving in both for now and deciding which one is best at the end.
> feat(element-storybook): layouts section

- packages/theme/src/lib/light-theme.ts
Removes focus on calendar icon when selecting a date with the mouse
> fix(theme): remove focus on datepicker icon button

- packages/breadcrumbs/src/lib/Breadcrumbs.test.tsx
- packages/breadcrumbs/src/lib/Breadcrumbs.tsx
Sets the default of `target` to `_top` for breadcrumbs. This is because we assume the crumbs will be used in the portal. This can be overridden through the config passed to the `crumbs` prop
> fix(mui-breadcrumbs): set default target on link to _top

- packages/theme/src/lib/legacy-theme.ts
Fixes an issue with the Popover using legacy theme where the elevation should default to 0.
Adds back legacy modal styles with the Dialog.
> fix(theme): add modal legacy styles

- packages/block-ui/src/lib/BlockUi.tsx
pass `className` to root component
> fix(mui-block-ui): pass className

- packages/autocomplete/README.md
- packages/autocomplete/src/index.ts
- packages/autocomplete/src/lib/AsyncAutocomplete.test.tsx
- packages/autocomplete/src/lib/AsyncAutocomplete.tsx
- packages/autocomplete/src/lib/Autocomplete.stories.tsx
- packages/autocomplete/src/lib/Autocomplete.tsx
Adds the `AsyncAutocomplete` component that uses the `loadOptions` prop to call for options
> feat(mui-autocomplete): add AsyncAutocomplete component

- apps/element-storybook/tsconfig.storybook.json
- packages/autocomplete/package.json
- packages/autocomplete/src/index.ts
- packages/autocomplete/src/lib/OrganizationAutocomplete.tsx
- packages/mock/src/lib/handlers.ts
- yarn.lock
Add export for `OrganizationAutocomplete` and a delay to the mock handler
> fix: add export and delay

- packages/datepicker/package.json
- packages/datepicker/src/lib/DateCalendar.tsx
- packages/datepicker/src/lib/Datepicker.stories.tsx
- packages/datepicker/src/lib/Datepicker.tsx
- packages/theme-provider/src/lib/theme-provider.tsx
- packages/theme/src/lib/legacy-theme.ts
- packages/theme/src/lib/light-theme.ts
- yarn.lock
- there is default aria-name for dialog, but if aria-labelledby is passed instead of label it takes precedence over name :)
- placeholder replaced with locale text at the theme-provider (localizationprovider) level.
- legacy day of week formatter types changed, moved out of theme and into component. Peeked at the datepicker specs and it looks like the new theme is also going with the two letter day abbrs like the legacy theme.
- swapped out the picker icon to match specs since I was already in there.
- did not look for any other light theme updates besides the x-date-picker update changes.
> fix(mui-datepicker): accessible dialog name and other updates

- packages/theme/src/lib/light-theme.ts
Currently everyone would need to set the body background color on their own. This means everyone has to realize this needs to be done and determine how to do this on their own. Most developers using workflow and coming from uikit will probably opt to [updating the scss](https://github.com/Availity/availity-starter-react/blob/a652adea39425505f4a4ac5b940d53e8151bc620/project/app/index.scss#L7-L9), but you can't (easily) pull the token values into scss so they will most likely hardcode it. To avoid hardcoding this commonly used body background color, it should just default to it.
Supersedes #639
> feat(theme): set the body background color

- packages/page-header/src/lib/PageHeader.tsx
>Warning: Each child in a list should have a unique "key" prop.
Check the render method of `PageHeader`. See https://reactjs.org/link/warning-keys for more information.
> fix(mui-page-header): pass key in map

- packages/controlled-form/src/lib/AsyncAutocomplete.tsx
- packages/controlled-form/src/lib/Checkbox.tsx
- packages/controlled-form/src/lib/CodesAutocomplete.tsx
- packages/controlled-form/src/lib/OrganizationAutocomplete.tsx
- packages/controlled-form/src/lib/ProviderAutocomplete.tsx
- packages/controlled-form/src/lib/Select.tsx
Not all of the component prop types are exported from the controlled form package. This exports all of the ones currently missing.
> fix(mui-controlled-form): export prop types

- packages/controlled-form/src/lib/TextField.tsx
Currently, the red asterisk does not appear when `ControlledTextField` has the `required` prop. This change forwards the `required` prop (converting it to a boolean) to the underlying `TextField` so that it displays the red asterisk.
> fix(mui-controlled-form): forward required from controlled text field to text field

- packages/controlled-form/src/lib/AsyncAutocomplete.tsx
- packages/controlled-form/src/lib/Autocomplete.tsx
- packages/controlled-form/src/lib/CodesAutocomplete.tsx
- packages/controlled-form/src/lib/Input.tsx
- packages/controlled-form/src/lib/OrganizationAutocomplete.tsx
- packages/controlled-form/src/lib/ProviderAutocomplete.tsx
- packages/controlled-form/src/lib/RadioGroup.tsx
- packages/controlled-form/src/lib/Select.tsx
- packages/controlled-form/src/lib/TextField.tsx
Currently, a nested property like `address.state`'s error styles will not appear. The errors object returned by RHF matches the structure of the underlying form, allowing nesting of objects and arrays accessed by index. Previously direct string access `errors[name]` resulted in something like `errors['address.state']` which would result in `undefined`. This PR changes it to use the `getFieldState` method provided by RHF which uses a `get` function similar to lodash's that works with dot and index notation in a string to traverse an object.
> fix(mui-controlled-form): support nested form properties

- packages/controlled-form/src/lib/AsyncAutocomplete.tsx
- packages/controlled-form/src/lib/Autocomplete.tsx
- packages/controlled-form/src/lib/CodesAutocomplete.tsx
- packages/controlled-form/src/lib/Datepicker.tsx
- packages/controlled-form/src/lib/Input.tsx
- packages/controlled-form/src/lib/OrganizationAutocomplete.tsx
- packages/controlled-form/src/lib/ProviderAutocomplete.tsx
- packages/controlled-form/src/lib/RadioGroup.tsx
- packages/controlled-form/src/lib/Select.tsx
- packages/controlled-form/src/lib/TextField.tsx
RHF's `required` prop can be a boolean, string, or object. In the case of object, the validation message and value (if the required validation enabled/disabled) are both present and he validation itself might be disabled (passing `false` to `value`.) While this is probably an edge-case, passing the previous code did not handle it and would set `required` to `true` when `{value: false}` was passed in resulting in the asterisk showing even though it is not required.
> fix(mui-controlled-form): support required prop object

- packages/controlled-form/src/lib/ControlledForm.tsx
A little opinionated, but I believe `ControlledForm`'s `form` should have `noValidate` by default. This will disable the browser-level validation in favor of the custom validations and styles.
Currently, when submitting a form with a required field (that has the required attribute) it will trigger the browser validation (with it's own error messages and styles) instead of element's validation and styles. This results in inconsistent validation.
Developers can manually add `noValidate`, but probably will not realize/remember to do it.
This defaults it so that element UX is used out of the box. It can be overridden by setting `noValidate={false}` if desired (IDK why)
> fix(mui-controlled-form): disable browser validation so custom errors can be shown

- packages/progress/src/lib/LinearProgress.test.tsx
- packages/progress/src/lib/LinearProgress.tsx
The ticket says "this ticket will turn off value prop (%) for LinearProgress indeterminate variant" so that is how it was coded. Let me know if this should be more configurable... allowing the percentage to be shown or not shown based on a prop regardless of the variant.
> fix(mui-progress): hide percentage for indeterminate

- packages/controlled-form/src/lib/AsyncAutocomplete.test.tsx
- packages/controlled-form/src/lib/AsyncAutocomplete.tsx
- packages/controlled-form/src/lib/Autocomplete.test.tsx
- packages/controlled-form/src/lib/Autocomplete.tsx
- packages/controlled-form/src/lib/Checkbox.tsx
- packages/controlled-form/src/lib/CodesAutocomplete.test.tsx
- packages/controlled-form/src/lib/CodesAutocomplete.tsx
- packages/controlled-form/src/lib/Datepicker.test.tsx
- packages/controlled-form/src/lib/Datepicker.tsx
- packages/controlled-form/src/lib/Input.tsx
- packages/controlled-form/src/lib/OrganizationAutocomplete.test.tsx
- packages/controlled-form/src/lib/OrganizationAutocomplete.tsx
- packages/controlled-form/src/lib/ProviderAutocomplete.test.tsx
- packages/controlled-form/src/lib/ProviderAutocomplete.tsx
- packages/controlled-form/src/lib/RadioGroup.tsx
- packages/controlled-form/src/lib/Select.tsx
- packages/controlled-form/src/lib/TextField.tsx
Fix regression introduced in #666 for using objects for `required` validation (more details about what that means in the original fix: #658)
Fix regression introduced in #666 for passing the `required` property through to underlying `TextField`s
The fixes include supporting the deprecated way of passing `required` directly as well as using the new `rules` object.
Added tests for all of these to prevent future regression.
> fix(mui-controlled-form): allow validation objects and forward required

- packages/page-header/src/lib/PageHeader.tsx
- add breadcrumbs placeholder to keep demo link & logo right aligned, but still left aligned after wrapping.
- add missing spacing when wrapped
> fix(mui-page-header): fix demo link and logo spacings

- packages/controlled-form/src/lib/Datepicker.tsx
the datepicker value must be a dayjs object or `null`, with the null coalescing (`??`) if the user passed an empty string, it will use that instead of null. Sometime people default to empty string, so this helps that use-case.
Other cases we have null coalescing are valid since those places cannot/should not be null. Datepicker is a special case where null is a valid value.
> fix(mui-controlled-form): fix issue with passing an empty string to datepicker

- packages/spaces/src/lib/SpacesLink/linkHandlers.tsx
- packages/spaces/src/lib/SpacesLink/useLink.test.tsx
Spaces UI is migrating to essentials so need to handle on prem relative URLs by converting them to absolute URLs
> refactor(mui-spaces): account for spaces-ui hosted in essentials
